#ifndef ASSETS_H
#define ASSETS_H

#define SHADER_SCREEN 0
#define SHADER_TEXTURE_2D 1
#define SHADER_TEXTURE_3D 2
#define SHADER_TEXTURE_3D_COLOR 3
#define SHADER_TEXTURE_3D_SHADOWED 4
#define SHADER_SHADOW_PASS 5
#define SHADER_VISUALIZE_DEPTH 6
#define SHADER_RENDER_MODEL 7
#define SHADER_RENDER_MODEL_SHADOWED 8
#define SHADER_HORIZONTAL_BLUR 9
#define SHADER_VERTICAL_BLUR 10
#define SHADER_SSAO 11
#define SHADER_GBUFFER 12
#define SHADER_RENDER_MODEL_GBUFFER 13
#define SHADER_SSAO_BLUR 14
#define SHADER_LIGHTING 15
#define SHADER_MODEL_SHADOW_PASS 16
#define SHADER_TEXTURE_2D_COLOR 17
#define SHADER_COUNT 18

#define SHADER_RENDER_MODEL_MAX_BONES 11

#define TEXTURE_BARON 0
#define TEXTURE_GRASS 1
#define TEXTURE_PLANK_FLOOR 2
#define TEXTURE_PLANKS 3
#define TEXTURE_STONE 4
#define TEXTURE_STONE_FLOOR 5
#define TEXTURE_PARTICLES 6
#define TEXTURE_SCENERY 7
#define TEXTURE_FONT 8
#define TEXTURE_COUNT 9

#define MUSIC_VAMPIRE_KILLER 0
#define MUSIC_COUNT 1

#define SOUND_BARON_SCREAM 0
#define SOUND_COUNT 1

#endif
